FROM nginx:alpine

# Copy secure nginx config
COPY nginx-secure.conf /etc/nginx/conf.d/default.conf

# Copy web content
COPY . /usr/share/nginx/html

# Remove default nginx configurations
RUN rm -f /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
